### ISSUE TITLE
mac csv

### ISSUE THREAD

**Issue by rachelgroves** [salk31/RedGiving#5]
doesn't work for import

**Comment by ghost** [comment]
what format are you saving in? it works for me with Windows Comma Separated (.csv) and Comma Separated Values (.csv)

**Comment by salk31** [comment]
Thanks for letting us know.

Geek notes:
I've done some digging around and Mac line ending might be '\r'. A colleague managed to produce a file like that and it was '\r' and UTF-8 without BOM.

**Comment by salk31** [comment]
Geek notes:
Will try http://stackoverflow.com/questions/1331815/regular-expression-to-match-cross-platform-newline-characters
